version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
  # Disable version updates, only security updates wanted
  # open-pull-requests-limit: 0

updates:
  - package-ecosystem: "cargo"
    directory: "/server"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "gradle"
    directory: "/AppAndroid"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  # - package-ecosystem: "swift"
  #   directory: "/AppiOS"
  #   patterns: ["*"]
  #   multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"

