name: AppiOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./AppiOS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: xcodebuild test -scheme MobileTiltMouse -destination "platform=iOS Simulator,name=iPhone 16" -only-testing MobileTiltMouseUITests/MobileTiltMouseUITests/testAlertError
    
      
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /Users/runner/Library/Developer/Xcode/DerivedData/MobileTiltMouse-*/Logs/Test/Test-MobileTiltMouse*.xcresult