name: AppiOS CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'AppiOS/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'AppiOS/**'
  workflow_dispatch:

jobs:
  test:
    name: AppiOS - Build and Test
    permissions:
      contents: read    
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./AppiOS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create certificates
        working-directory: ./server
        run: cargo build  

      - name: Set device
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          echo "device_name=$device" >> "$GITHUB_ENV"

      - name: Build for testing
        run: xcodebuild build-for-testing -scheme MobileTiltMouse -destination "platform=iOS Simulator,name=$device_name"

      - name: Unit tests
        run: xcodebuild test-without-building -scheme MobileTiltMouse -destination "platform=iOS Simulator,name=$device_name" -only-testing MobileTiltMouseTests

      # UI tests do not run reliably on GitHub, although they do locally: Therefore UI test are disabled
      # - name: UI tests
      #   run: xcodebuild test-without-building -scheme MobileTiltMouse -destination "platform=iOS Simulator,name=$device_name" -only-testing MobileTiltMouseUITests/MobileTiltMouseUITests

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: /Users/runner/Library/Developer/Xcode/DerivedData/MobileTiltMouse-*/Logs/Test/Test-MobileTiltMouse*.xcresult

