name: server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Server - Build and Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./server  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get rust version
        run: rustc --version --verbose
      - name: Get cargo version
        run: cargo --version --verbose
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: server-${{ runner.os }}-${{ hashFiles('**/server/Cargo.lock') }}
      - if: runner.os == 'Linux'
        name: Install additional packages
        run: sudo apt update && sudo apt install -y libxdo-dev xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev clang avahi-daemon libavahi-client-dev
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -Dwarnings
      - name: Run unit tests
        run: cargo test --lib
